# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 667ca0735c1164b10f8ad5b8b879b8c7c9af153ff9a59959c2af0267740b6ac1ce966ff3ed13d4ad26f7c48f3d11e74b579bf78d5a7e827c169186c0d44ffaea

test:
  secret_key_base: 7f59ff20fbb1dc3b839e710a76415173b1b1c6870c8d98169f9e783981066df72a45c83bdb556735c8048d782ae6f9d7a83ab1a4e77e9c1e33ce92bb5bf39e6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
